title: Lihe Liu
permalink: ':title/'
url: "https://victorlin.github.io"

# Author Settings
author: Lihe Liu
author-img: made-in-2013-thumb.jpg
github: liulihe954
linkedin: liheliu95
email: lihe.liu@ufl.edu
#google_scholar: DrzHirYAAAAJ

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-redirect-from

paginate: 8
paginate_path: "blog/page/:num"

collections:
  mashups:
    output: true
  videos:
    output: true
  project:
    output: true
  talks:
    output: true
  software:
    output: true

sass:
    sass_dir: assets/css/scss

analytics: UA-109654720-1

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
